baseurl = "/"
languageCode = "en-us"
title = "Xiaoqi Tan"
theme = "hugo-xmin"
googleAnalytics = "UA-153197636-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 3
[[menu.main]]
    name = "Resume"
    weight = 4
    url = "/resume"
[[menu.main]]
    name = "Contact"
    weight = 5
    url = "/#contact"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Xiaoqi Tan](https://xiaoqitan.org) 2018--2020"

  

[blackfriday]
hrefTargetBlank = true